### ISSUE TITLE
Use the library in Espruino

### ISSUE THREAD

**Issue by csanz91** [rovale/micro-mqtt#250]
Hi, I have found this amazing library and I am trying to use it with Espruino. 
I'm using the command `npm run deploy` which successfully creates the the `micro-mqtt.js` file and I can also see the module in the Espruino IDE. However, when running the example that is generated, I can see several unmet dependencies: 
```
Module ./ConnectReturnCode not found
Module ./ConnectFlags not found
Module ./ControlPacketType not found
Module events not found
```
I also have tried to copy all the .js files generated in the bin/module folder to the Espruino without any luck.
Any idea about what I am doing wrong?
Thank you

**Comment by rovale** [comment]
Hi Cesar, thanks for your compliment! 😃

Like I said in the description of this repository, don't use it for anything serious. At some point I got it working on the Espruino. Later on I made some modifications which might have broken it, I never tested it anymore.

Maybe you can try it with the commit before this one? https://github.com/rovale/micro-mqtt/commit/9d39474b364ce5145fe42cee378d8233c91c6d4c

If you manage to get it working, I am happy to merge any PR.

Wish you all the best!

**Comment by csanz91** [comment]
Hi, after some testing with the different commits, I have found that [this is the commit](https://github.com/rovale/micro-mqtt/commit/f3a7b71fba22ad95d8c81899339fdd4b8078c9a4) where the compatibility with the Espruino gets broken. 
I have compiled the version before that commit and apparently everything looks fine in the Espruino, I have been able to connect and publish a message.
I think I will give it a try because I really want to use features like the retained messages, or the Will Testament, that the standard library doesn't provide.

Regards

**Comment by rovale** [comment]
Hi Cesar, happy to hear it works for you now! So I broke it by blindly obeying the tslint rules. Indeed the changes relate to the unmet dependencies.

Also very happy to hear you are planning to use the features I added!

Please let me know about your findings. Maybe it is worthwhile to rollback the latest changes after all.

**Comment by rovale** [comment]
Maybe I will test it myself next weekend: https://github.com/rovale/micro-mqtt/pull/255.

😄

**Comment by csanz91** [comment]
Hi, I just want to report that with the latests commits everything has been running smoothly for the last 2 days, very stable so far.
 These are the features I have been using: 
- Publish/Subscribe
- Last Will
- Retained messages
- Auto reconnection
I think we can close the issue. Thank you @rovale!

**Comment by rovale** [comment]
This is great news! Thanks a lot for testing it out!
