### ISSUE TITLE
"Got EOF expected '}' "when uploading example to esp8266

### ISSUE THREAD

**Issue by rbedemann** [rovale/micro-mqtt#287]
When I upload the [example.js](https://github.com/rovale/micro-mqtt/blob/master/espruino/projects/example.js) file from espruino directory, I get 
`Uncaught SyntaxError: Got EOF expected '}'`

I tried also in my own project, but get the same error. My espruino version is 2v01.

Any ideas what I'm doing wrong?

**Comment by rovale** [comment]
I just tried it on (on 2v00) and it works for me.

![image](https://user-images.githubusercontent.com/7162608/55193375-0cf0b280-51a7-11e9-89fe-d1db2a3651df.png)

To be honest Espruino does not really have my focus right now. I am currently into ESP32 with the Arduino framework. Stable, secure, simple. :-)

https://github.com/rovale/SimpleInternetThing
